kumuluzee:
  name: nakupovalni-seznami
  version: 1.0.0
  env:
      name: dev
  datasources:
    - jndi-name: jdbc/NakupovalniSeznamiDS
      connection-url: jdbc:postgresql://ps:5432/nakupovalniseznami
      username: postgres
      password: postgres
      max-pool-size: 20
  openapi:
    ui:
      enabled: true
  health:
    checks:
      disk-space-health-check:
        threshold: 100000000
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/NakupovalniSeznamiDS