kumuluzee:
  name: nakupovalni-seznami
  version: 1.0.0
  env:
      name: dev
  datasources:
    - jndi-name: jdbc/NakupovalniSeznamiDS
      connection-url: jdbc:postgresql://localhost:5432/nakupovalniseznami
      username: postgres
      password: postgres
      max-pool-size: 20
  openapi:
    ui:
      enabled: true